version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "HT"
    main: ./cmd/ht/main.go
    binary: ht
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "ht-{{ .Os }}-{{ .Arch }}"
    format: zip
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'

release:
  github:
    owner: franciscorojas27
    name: HT